#pragma once

namespace OBJID
{
	enum ID { BOMB,PLAYER, ENEMY, ENEMY_BULLET, SHIELD,PLAYER_BULLET, UI, MENUUI, MOUSE, END };
}

enum FRAME_STATE { NONE, NEXT, FINISH};


enum BULLET
{
	REDSMALL, REDBIG, REDSNOW, BLUEBIG, BLUESMALL, BLUESNOW, BULLET_END
};

enum PATERN
{
	GATLING,STOPMOVE, SPREAD, BOUNCE, PATERN_END
};